# Generated by Django 3.2.8 on 2021-11-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('id', models.IntegerField(max_length=10, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('remark', models.CharField(max_length=255, verbose_name='Remark')),
                ('progress_percentage', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Progress Percentage')),
                ('victim_number', models.IntegerField(max_length=5, verbose_name='Victim Number')),
                ('is_approved', models.BooleanField(verbose_name='Is Approve')),
                ('user_id', models.IntegerField(max_length=5, verbose_name='User ID')),
                ('assistance_type_id', models.IntegerField(max_length=5, verbose_name='Assistance Type ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
            ],
        ),
        migrations.CreateModel(
            name='Assistance_type',
            fields=[
                ('id', models.IntegerField(max_length=10, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('detail', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Detail')),
                ('assistance_given_date', models.IntegerField(max_length=8, verbose_name='Assistance Given Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
            ],
        ),
    ]
