# Generated by Django 3.2.8 on 2021-11-26 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistance_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assistance_type',
            new_name='AssistanceType',
        ),
        migrations.RemoveField(
            model_name='assistance',
            name='assistance_type_id',
        ),
        migrations.AddField(
            model_name='assistance',
            name='assistance_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assistance_app.assistancetype'),
            preserve_default=False,
        ),
    ]
