# Generated by Django 3.2.8 on 2021-11-26 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assistance_app', '0002_auto_20211126_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistance',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='assistancetype',
            name='assistance_given_date',
        ),
        migrations.AddField(
            model_name='assistance',
            name='assistance_given_date',
            field=models.DateTimeField(null=True, verbose_name='Assistance Given Date'),
        ),
        migrations.AddField(
            model_name='assistance',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assistance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='remark',
            field=models.TextField(verbose_name='Remark'),
        ),
        migrations.AlterField(
            model_name='assistancetype',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='assistancetype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
