# Generated by Django 3.2.8 on 2021-11-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance_app', '0004_auto_20211126_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='progress_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Progress Percentage'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='Remark'),
        ),
    ]
