# Generated by Django 3.2.8 on 2021-11-27 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance_app', '0005_auto_20211127_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Is Approved'),
        ),
    ]
