# Generated by Django 3.2.8 on 2021-12-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance_app', '0008_alter_assistance_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistance',
            name='ic',
            field=models.CharField(default='', max_length=255, verbose_name='Ic'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='victim_number',
            field=models.IntegerField(verbose_name='Victim Number'),
        ),
    ]
