# Generated by Django 3.2.8 on 2021-12-05 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistance_app', '0009_auto_20211205_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance',
            name='assistance_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assistance_app.assistancetype'),
        ),
    ]
