# Generated by Django 3.2.8 on 2021-12-09 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistance_app', '0010_alter_assistance_assistance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance',
            name='assistance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistance_type', to='assistance_app.assistancetype'),
        ),
    ]
