# Generated by Django 3.2.8 on 2021-12-09 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assistance_app', '0011_alter_assistance_assistance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistance', to=settings.AUTH_USER_MODEL),
        ),
    ]
