# Generated by Django 3.2.8 on 2021-12-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('ic', models.IntegerField(primary_key=True, serialize=False, verbose_name='IC')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('phone', models.IntegerField(verbose_name='Phone Number')),
                ('is_kir', models.BooleanField(default=True, verbose_name='Ketua Isi Rumah')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Salary')),
                ('address1', models.CharField(max_length=255, verbose_name='Address1')),
                ('address2', models.CharField(max_length=255, verbose_name='Address2')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('mukim', models.CharField(max_length=255, verbose_name='Mukim')),
                ('parlimen', models.CharField(max_length=255, verbose_name='Parlimen')),
                ('state', models.CharField(max_length=255, verbose_name='State')),
                ('poskod', models.IntegerField(verbose_name='Poskod')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
        ),
    ]
