# Generated by Django 3.2.8 on 2021-12-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victim_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ic',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Ic'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='poskod',
            field=models.CharField(max_length=255, verbose_name='Phone'),
        ),
    ]
