# Generated by Django 3.2.8 on 2021-11-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victim_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='address',
            name='poskod',
            field=models.IntegerField(verbose_name='Poskod'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ic',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='IC'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(verbose_name='Phone Number'),
        ),
    ]
